# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:1234@tcp(127.0.0.1:3306)/gateway?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 200
        max_idle_conn = 100
        max_conn_life_time = 100